-- Drop all schemas (cascading will drop all tables within)
DROP SCHEMA IF EXISTS sch_auth CASCADE;
DROP SCHEMA IF EXISTS sch_user CASCADE;
DROP SCHEMA IF EXISTS sch_config CASCADE;
DROP SCHEMA IF EXISTS sch_director CASCADE;
DROP SCHEMA IF EXISTS sch_task CASCADE;
DROP SCHEMA IF EXISTS sch_planning CASCADE;
DROP SCHEMA IF EXISTS sch_mpt CASCADE;
DROP SCHEMA IF EXISTS sch_situation CASCADE;
DROP SCHEMA IF EXISTS sch_voice CASCADE;
DROP SCHEMA IF EXISTS sch_dict CASCADE;
DROP SCHEMA IF EXISTS sch_agent CASCADE;
DROP SCHEMA IF EXISTS sch_report CASCADE;
DROP SCHEMA IF EXISTS sch_record CASCADE;
DROP SCHEMA IF EXISTS sch_admin CASCADE;
