// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_api_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReq) Reset() {
	*x = ListUsersReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReq) ProtoMessage() {}

func (x *ListUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReq.ProtoReflect.Descriptor instead.
func (*ListUsersReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *ListUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type UserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	LastLogin     string                 `protobuf:"bytes,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_api_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserItem) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserItem) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UserItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserItem) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

type ListUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserItem            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResp) Reset() {
	*x = ListUsersResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResp) ProtoMessage() {}

func (x *ListUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResp.ProtoReflect.Descriptor instead.
func (*ListUsersResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResp) GetList() []*UserItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListUsersResp) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	OperatorId    int64                  `protobuf:"varint,6,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *CreateUserReq) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateUserReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Status        *int32                 `protobuf:"varint,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	OperatorId    int64                  `protobuf:"varint,7,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorRoles []string               `protobuf:"bytes,8,rep,name=operator_roles,json=operatorRoles,proto3" json:"operator_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UpdateUserReq) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UpdateUserReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateUserReq) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateUserReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *UpdateUserReq) GetOperatorRoles() []string {
	if x != nil {
		return x.OperatorRoles
	}
	return nil
}

type UpdateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResp) Reset() {
	*x = UpdateUserResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResp) ProtoMessage() {}

func (x *UpdateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResp.ProtoReflect.Descriptor instead.
func (*UpdateUserResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{7}
}

type DeleteUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReq) Reset() {
	*x = DeleteUserReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReq) ProtoMessage() {}

func (x *DeleteUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReq.ProtoReflect.Descriptor instead.
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeleteUserReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DeleteUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResp) Reset() {
	*x = DeleteUserResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResp) ProtoMessage() {}

func (x *DeleteUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResp.ProtoReflect.Descriptor instead.
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserResp) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type BatchDeleteUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteUsersReq) Reset() {
	*x = BatchDeleteUsersReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteUsersReq) ProtoMessage() {}

func (x *BatchDeleteUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteUsersReq.ProtoReflect.Descriptor instead.
func (*BatchDeleteUsersReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *BatchDeleteUsersReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchDeleteUsersReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type BatchDeleteUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteUsersResp) Reset() {
	*x = BatchDeleteUsersResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteUsersResp) ProtoMessage() {}

func (x *BatchDeleteUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteUsersResp.ProtoReflect.Descriptor instead.
func (*BatchDeleteUsersResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *BatchDeleteUsersResp) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type GetProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReq) Reset() {
	*x = GetProfileReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReq) ProtoMessage() {}

func (x *GetProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReq.ProtoReflect.Descriptor instead.
func (*GetProfileReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResp) Reset() {
	*x = GetProfileResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResp) ProtoMessage() {}

func (x *GetProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResp.ProtoReflect.Descriptor instead.
func (*GetProfileResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetProfileResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProfileResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileResp) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *GetProfileResp) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *GetProfileResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetProfileResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetProfileResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Department    string                 `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileReq) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UpdateProfileReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateProfileReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResp) Reset() {
	*x = UpdateProfileResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResp) ProtoMessage() {}

func (x *UpdateProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateProfileResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{15}
}

type GetOrgTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgTreeReq) Reset() {
	*x = GetOrgTreeReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgTreeReq) ProtoMessage() {}

func (x *GetOrgTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgTreeReq.ProtoReflect.Descriptor instead.
func (*GetOrgTreeReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{16}
}

type OrgTreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	ParentId      int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Children      []*OrgTreeNode         `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgTreeNode) Reset() {
	*x = OrgTreeNode{}
	mi := &file_api_proto_user_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgTreeNode) ProtoMessage() {}

func (x *OrgTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgTreeNode.ProtoReflect.Descriptor instead.
func (*OrgTreeNode) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{17}
}

func (x *OrgTreeNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrgTreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgTreeNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrgTreeNode) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *OrgTreeNode) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *OrgTreeNode) GetChildren() []*OrgTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetOrgTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*OrgTreeNode         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgTreeResp) Reset() {
	*x = GetOrgTreeResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgTreeResp) ProtoMessage() {}

func (x *GetOrgTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgTreeResp.ProtoReflect.Descriptor instead.
func (*GetOrgTreeResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetOrgTreeResp) GetNodes() []*OrgTreeNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CreateOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	OperatorId    int64                  `protobuf:"varint,5,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationReq) Reset() {
	*x = CreateOrganizationReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationReq) ProtoMessage() {}

func (x *CreateOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationReq.ProtoReflect.Descriptor instead.
func (*CreateOrganizationReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{19}
}

func (x *CreateOrganizationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateOrganizationReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateOrganizationReq) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateOrganizationReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type CreateOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResp) Reset() {
	*x = CreateOrganizationResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResp) ProtoMessage() {}

func (x *CreateOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResp.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{20}
}

func (x *CreateOrganizationResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateOrganizationResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationReq) Reset() {
	*x = DeleteOrganizationReq{}
	mi := &file_api_proto_user_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationReq) ProtoMessage() {}

func (x *DeleteOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationReq.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationReq) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteOrganizationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteOrganizationReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DeleteOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationResp) Reset() {
	*x = DeleteOrganizationResp{}
	mi := &file_api_proto_user_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationResp) ProtoMessage() {}

func (x *DeleteOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationResp.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationResp) Descriptor() ([]byte, []int) {
	return file_api_proto_user_user_proto_rawDescGZIP(), []int{22}
}

var File_api_proto_user_user_proto protoreflect.FileDescriptor

const file_api_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/user/user.proto\x12\x04user\"Q\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"Y\n" +
	"\fListUsersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"\xbe\x01\n" +
	"\bUserItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"last_login\x18\a \x01(\tR\tlastLogin\"`\n" +
	"\rListUsersResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.UserItemR\x04list\x12+\n" +
	"\tpage_info\x18\x02 \x01(\v2\x0e.user.PageInfoR\bpageInfo\"\xb9\x01\n" +
	"\rCreateUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1f\n" +
	"\voperator_id\x18\x06 \x01(\x03R\n" +
	"operatorId\"<\n" +
	"\x0eCreateUserResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xfc\x01\n" +
	"\rUpdateUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x1f\n" +
	"\voperator_id\x18\a \x01(\x03R\n" +
	"operatorId\x12%\n" +
	"\x0eoperator_roles\x18\b \x03(\tR\roperatorRolesB\t\n" +
	"\a_status\"\x10\n" +
	"\x0eUpdateUserResp\"B\n" +
	"\rDeleteUserReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"5\n" +
	"\x0eDeleteUserResp\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"H\n" +
	"\x13BatchDeleteUsersReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\";\n" +
	"\x14BatchDeleteUsersResp\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"(\n" +
	"\rGetProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xd1\x01\n" +
	"\x0eGetProfileResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\"\x8f\x01\n" +
	"\x10UpdateProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"department\x18\x02 \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"\x13\n" +
	"\x11UpdateProfileResp\"\x0f\n" +
	"\rGetOrgTreeReq\"\xb0\x01\n" +
	"\vOrgTreeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12-\n" +
	"\bchildren\x18\x06 \x03(\v2\x11.user.OrgTreeNodeR\bchildren\"9\n" +
	"\x0eGetOrgTreeResp\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.user.OrgTreeNodeR\x05nodes\"\x9c\x01\n" +
	"\x15CreateOrganizationReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x1f\n" +
	"\voperator_id\x18\x05 \x01(\x03R\n" +
	"operatorId\"<\n" +
	"\x16CreateOrganizationResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\x15DeleteOrganizationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"\x18\n" +
	"\x16DeleteOrganizationResp2\x8f\x05\n" +
	"\vUserService\x124\n" +
	"\tListUsers\x12\x12.user.ListUsersReq\x1a\x13.user.ListUsersResp\x127\n" +
	"\n" +
	"CreateUser\x12\x13.user.CreateUserReq\x1a\x14.user.CreateUserResp\x127\n" +
	"\n" +
	"UpdateUser\x12\x13.user.UpdateUserReq\x1a\x14.user.UpdateUserResp\x127\n" +
	"\n" +
	"DeleteUser\x12\x13.user.DeleteUserReq\x1a\x14.user.DeleteUserResp\x12I\n" +
	"\x10BatchDeleteUsers\x12\x19.user.BatchDeleteUsersReq\x1a\x1a.user.BatchDeleteUsersResp\x127\n" +
	"\n" +
	"GetProfile\x12\x13.user.GetProfileReq\x1a\x14.user.GetProfileResp\x12@\n" +
	"\rUpdateProfile\x12\x16.user.UpdateProfileReq\x1a\x17.user.UpdateProfileResp\x127\n" +
	"\n" +
	"GetOrgTree\x12\x13.user.GetOrgTreeReq\x1a\x14.user.GetOrgTreeResp\x12O\n" +
	"\x12CreateOrganization\x12\x1b.user.CreateOrganizationReq\x1a\x1c.user.CreateOrganizationResp\x12O\n" +
	"\x12DeleteOrganization\x12\x1b.user.DeleteOrganizationReq\x1a\x1c.user.DeleteOrganizationRespB\x1cZ\x1aitms-server/api/proto/userb\x06proto3"

var (
	file_api_proto_user_user_proto_rawDescOnce sync.Once
	file_api_proto_user_user_proto_rawDescData []byte
)

func file_api_proto_user_user_proto_rawDescGZIP() []byte {
	file_api_proto_user_user_proto_rawDescOnce.Do(func() {
		file_api_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_user_user_proto_rawDesc), len(file_api_proto_user_user_proto_rawDesc)))
	})
	return file_api_proto_user_user_proto_rawDescData
}

var file_api_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_user_user_proto_goTypes = []any{
	(*PageInfo)(nil),               // 0: user.PageInfo
	(*ListUsersReq)(nil),           // 1: user.ListUsersReq
	(*UserItem)(nil),               // 2: user.UserItem
	(*ListUsersResp)(nil),          // 3: user.ListUsersResp
	(*CreateUserReq)(nil),          // 4: user.CreateUserReq
	(*CreateUserResp)(nil),         // 5: user.CreateUserResp
	(*UpdateUserReq)(nil),          // 6: user.UpdateUserReq
	(*UpdateUserResp)(nil),         // 7: user.UpdateUserResp
	(*DeleteUserReq)(nil),          // 8: user.DeleteUserReq
	(*DeleteUserResp)(nil),         // 9: user.DeleteUserResp
	(*BatchDeleteUsersReq)(nil),    // 10: user.BatchDeleteUsersReq
	(*BatchDeleteUsersResp)(nil),   // 11: user.BatchDeleteUsersResp
	(*GetProfileReq)(nil),          // 12: user.GetProfileReq
	(*GetProfileResp)(nil),         // 13: user.GetProfileResp
	(*UpdateProfileReq)(nil),       // 14: user.UpdateProfileReq
	(*UpdateProfileResp)(nil),      // 15: user.UpdateProfileResp
	(*GetOrgTreeReq)(nil),          // 16: user.GetOrgTreeReq
	(*OrgTreeNode)(nil),            // 17: user.OrgTreeNode
	(*GetOrgTreeResp)(nil),         // 18: user.GetOrgTreeResp
	(*CreateOrganizationReq)(nil),  // 19: user.CreateOrganizationReq
	(*CreateOrganizationResp)(nil), // 20: user.CreateOrganizationResp
	(*DeleteOrganizationReq)(nil),  // 21: user.DeleteOrganizationReq
	(*DeleteOrganizationResp)(nil), // 22: user.DeleteOrganizationResp
}
var file_api_proto_user_user_proto_depIdxs = []int32{
	2,  // 0: user.ListUsersResp.list:type_name -> user.UserItem
	0,  // 1: user.ListUsersResp.page_info:type_name -> user.PageInfo
	17, // 2: user.OrgTreeNode.children:type_name -> user.OrgTreeNode
	17, // 3: user.GetOrgTreeResp.nodes:type_name -> user.OrgTreeNode
	1,  // 4: user.UserService.ListUsers:input_type -> user.ListUsersReq
	4,  // 5: user.UserService.CreateUser:input_type -> user.CreateUserReq
	6,  // 6: user.UserService.UpdateUser:input_type -> user.UpdateUserReq
	8,  // 7: user.UserService.DeleteUser:input_type -> user.DeleteUserReq
	10, // 8: user.UserService.BatchDeleteUsers:input_type -> user.BatchDeleteUsersReq
	12, // 9: user.UserService.GetProfile:input_type -> user.GetProfileReq
	14, // 10: user.UserService.UpdateProfile:input_type -> user.UpdateProfileReq
	16, // 11: user.UserService.GetOrgTree:input_type -> user.GetOrgTreeReq
	19, // 12: user.UserService.CreateOrganization:input_type -> user.CreateOrganizationReq
	21, // 13: user.UserService.DeleteOrganization:input_type -> user.DeleteOrganizationReq
	3,  // 14: user.UserService.ListUsers:output_type -> user.ListUsersResp
	5,  // 15: user.UserService.CreateUser:output_type -> user.CreateUserResp
	7,  // 16: user.UserService.UpdateUser:output_type -> user.UpdateUserResp
	9,  // 17: user.UserService.DeleteUser:output_type -> user.DeleteUserResp
	11, // 18: user.UserService.BatchDeleteUsers:output_type -> user.BatchDeleteUsersResp
	13, // 19: user.UserService.GetProfile:output_type -> user.GetProfileResp
	15, // 20: user.UserService.UpdateProfile:output_type -> user.UpdateProfileResp
	18, // 21: user.UserService.GetOrgTree:output_type -> user.GetOrgTreeResp
	20, // 22: user.UserService.CreateOrganization:output_type -> user.CreateOrganizationResp
	22, // 23: user.UserService.DeleteOrganization:output_type -> user.DeleteOrganizationResp
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_user_user_proto_init() }
func file_api_proto_user_user_proto_init() {
	if File_api_proto_user_user_proto != nil {
		return
	}
	file_api_proto_user_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_user_user_proto_rawDesc), len(file_api_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_user_user_proto_goTypes,
		DependencyIndexes: file_api_proto_user_user_proto_depIdxs,
		MessageInfos:      file_api_proto_user_user_proto_msgTypes,
	}.Build()
	File_api_proto_user_user_proto = out.File
	file_api_proto_user_user_proto_goTypes = nil
	file_api_proto_user_user_proto_depIdxs = nil
}
